#!/bin/bash
#
#	/etc/rc.d/init.d/ncdd_client
#
# Starts the ncdd_client daemon
#
# chkconfig: 345 99 10
# description: Runs commands scheduled by the at command at the time \
#    specified when at was run, and runs batch commands when the load \
#    average is low enough.
# processname: ncdd_client

# Source function library.
. /etc/init.d/functions

test -x /sbin/ncdd_client || exit 0

RETVAL=0

#
#	See how we were called.
#

prog="ncdd_client"

start() {
	# Check if atd is already running
	if [ ! -f /var/lock/subsys/ncdd_client ]; then
	    modprobe ncdd
	    echo -n $"Iniciando $prog: "
	    daemon /sbin/ncdd_client
#	    /sbin/ncdd_client >> /var/log/ncdd_client.log &
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/ncdd_client
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Deteniendo $prog: "
	killproc /sbin/ncdd_client
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/ncdd_client
	echo
	rmmod ncdd
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	restart
}	

status_at() {
 	status /sbin/ncdd_client
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/ncdd_client ]; then
	    restart
	fi
	;;
status)
	status_at
	;;
*)
	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac

exit $?
exit $RETVAL
