#!/bin/sh
#
# chkconfig: 345 70 8
# description: Server ncdd
#
### BEGIN INIT INFO
# Provides: ncdd_server
# Required-Start: $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: Servei ncdd_server
### END INIT INFO

DAEMON_NAME="ncdd_server"
DAEMON_BIN="/sbin/ncdd_server"
DAEMON_OPTS=""
PROCESS_NAME="/sbin/ncdd_server"
SCRIPTNAME=ncdd_server

DAEMON_RESTART_LOCK=/var/run/restarting_$DAEMON_NAME
LOCKFILE=/var/lock/subsys/$SCRIPTNAME


status_ps()
{

PIDS=`ps --columns 400 aux|grep "$PROCESS_NAME"|grep -v "grep"|awk '{printf "%s ",$2 }'`
if [ -z "$PIDS" ]; then
	echo "not running"
	return 3
fi

echo "running"
return 0

}

status()
{

status_ps

}

case $1 in
start)
status  > /dev/null 2>&1
if [ $? == 0 ]; then
	echo "$DAEMON_NAME ja executant-se"
	exit 0
fi

echo "Iniciant $DAEMON_NAME"
[ -d /var/lock/subsys ] && touch $LOCKFILE  # for RedHat
$DAEMON_BIN $DAEMON_OPTS
;;

stop)
echo "Aturant $DAEMON_NAME"

DAEMON_RUN=1
PAUSE=0
TIMEOUT=10
while [ $DAEMON_RUN == 1 -a $PAUSE != $TIMEOUT ]; do

	status_ps > /dev/null 2>&1

	if [ $? != 0 ]; then
		DAEMON_RUN=0
	fi
	PIDS=`ps --columns 400 aux|grep "$PROCESS_NAME"|grep -v "grep"|awk '{printf "%s ",$2 }'`

	for i in $PIDS; do
		kill -TERM $i
	done


	echo -n "."
	PAUSE=$(($PAUSE+1))
	sleep 1
done

[ -f $LOCKFILE ] && rm -f $LOCKFILE

;;

reload)
echo "Recarregant $DAEMON_NAME"
        PIDS=`ps --columns 400 aux|grep "$PROCESS_NAME"|grep -v "grep"|awk '{printf "%s ",$2 }'`

        for i in $PIDS; do
                kill -HUP $i
        done

;;

restart)
touch $DAEMON_RESTART_LOCK
$0 stop
$0 start
rm -f $DAEMON_RESTART_LOCK
;;

status)
echo -n "Comprovant $DAEMON_NAME ... "

#Si esta reiniciant el servei, retornar OK, per tal de no alertar el heartbeat
if [ -e $DAEMON_RESTART_LOCK ]; then
        echo "restarting. running"
	exit 0
fi
		

status 
exit $?
;;

*)
echo "$0 {start|stop|status|restart|reload}"
;;
esac

exit 0 
